transform_height = 128
transform_width = 128
img_channels = 4
batch_size = 32  # batch size for update in exp replay
eps_start = 0.9
eps_end = 0.05
eps_decay = 200
observe = 128  # start training after this timestep
gamma = 0.9
num_of_actions = 9  # stop, left, right, up, down, left-up, left-down, right-up, right-down
death_reward = -100  # at the moment the agent stays dead for two frames, so it will receive this reward twice
reward_in_env = 1  # reward for living in the environment
reward_on_power = 20  # reward for getting power item
timesteps_to_save_weights = 500  # saves weights at these iterations of timesteps
exp_replay_memory = 10000  # length of exp replay deque before popping values
