transform_height = 128
transform_width = 128
img_channels = 12
batch_size = 32  # batch size for update in exp replay
eps_start = 0.9
eps_end = 0.05
eps_decay = 1000
observe = 1000  # start training after this timestep
gamma = 0.9
num_of_actions = 5  # 9  # stop, left, right, up, down, left-up, left-down, right-up, right-down
death_reward = -100  # at the moment the agent stays dead for two frames, so it will receive this reward twice
reward_in_env = 1  # reward for living in the environment
reward_on_power = 5  # reward for getting power item
reward_on_hit = 0  # reward for hitting enemy
reward_on_dodge = 0  # reward for dodge
timesteps_to_save_weights = 500  # saves weights at these iterations of timesteps
exp_replay_memory = 10000  # length of exp replay deque before popping values
